version: '3.7'

services:
  webapp-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp-server-img
    container_name: myapp-node-express
    volumes:
       - .:/usr/src/app
       - /usr/src/app/node_modules
    ports:
        - "5000:5000"
    depends_on:
        - mongo
    env_file: .env
    environment:
      JWT_SECRET: abc123
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb+srv://roozbeh123:roozbeh123@cluster0.skexl.mongodb.net/proshop?retryWrites=true&w=majority  
      ZARIN_PAL_MERCHANT_ID: 4ced0a1e-4ad8-4309-9668-3ea3ae8e8897
      ZARINPAL_URL: https://api.zarinpal.com/pg/v4/payment/request.json
      
  mongo:
    image: mongo
    container_name: myapp-mongodb
    ports:
      - "27017:27017"