apiVersion: apps/v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: arvan-test
  labels:
    app: nginx
spec:
accessModes:
- ReadWriteOnce
resources:
  requests:
    storage: 1G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  spec: 
   replicas: 1
   template:
     labels: 
       app: mongodb
spec:
containers:
- name: mongodb
  resources: 
   limits: 
    cpu: 1500m
    ephemeral-storage: 1G
    memory: 600M
  requests: 
   cpu: 1500m
   ephemeral-storage: 1G
   memory: 600M
image: mongo:4.0.4
ports: 
  - containerPort: 27017
    name: mongodb-port
volumeMounts: 
  - mountPath: /data/db
    name: mongodb-pvc
volumes: 
- name: mongodb-pvc
  PersistentVolumeClaim:
    claimName: mongodb-pvc
selector:
   matchLabels:
   app: mongodb

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  spec:
   ports: 27017
   protocol: TCP
   selector:
     app: mongodb
     type: ClusterIp

---
apiVersion: app/v1
kind: Deployment
metadata:
  name: cloud1-server-deployment
  spec: 
   replicas: 1
   template:
     labels: 
       app: cloud1-server
       resources: 
   limits: 
     cpu: 1500m
     ephemeral-storage: 1G
     memory: 600M
  image: arvanpaas/mern_server:v1
  ports: 
  - containerPort: 5000
    name: nodejs-port
selector:
   matchLabels:
   app: cloud1-server

---
apiVersion: v1
kind: Service
metadata:
  name: cloud1-server-service
  spec:
   ports: 5000
   protocol: TCP
  selector:
    app: cloud1-server
    type: ClusterIp

---
apiVersion: app/v1
kind: Deployment
metadata:
  name: cloud1-server-service
  spec: 
   ports: 
   - port: 5000
     protocol: TCP
selector:
   app: cloud1-server
   type: ClusterIp

---
apiVersion: app/v1
kind: Deployment
metadata:
  name: cloud1-client-deployment
spec:
  selector:
    matchLabels:
      app: cloud1-client
    replicas: 1
  template:
     metadata:
       labels: 
         app: cloud1-client
  spec: 
   containers:
   - name: cloud1-client
     image: arvanpaas/mern_client:v1
     resources:
      limits: 
       cpu: 1500m
       ephemeral-storage: 1G
       memory: 600M
      requests:
        cpu: 1500m
        ephemeral-storage: 1G
        memory: 600m
      ports: 
      - containerPort: 80
        name: http-port
  

---
apiVersion: v1
kind: Service
metadata:
  name: cloud1-client
  spec:
   - ports: 80
     protocol: TCP
     targetPort: 80
     name: http
  selector:
    app: cloud1-client
    type: ClusterIp

---
apiVersion: route.openshift.io/v1
kind: Route 
metadata: 
  name: cloud1-client-route
  namespace: arvan-test
spec:
  host: cloud1-client-arvan-test.app.ir-thr-at1.arvan.run
  port: 
    targetPort: http
  tls: 
    insecureEdgeTerminationPolicy: Redirect
    termination: edge 
  to: 
    kind: service 
    name: cloud1-client  

    

















